[package]
name = "on_cart_for_thee"
version = "1.0.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3