name: On Cart For Thee - CI/CD

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy on the default branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - run: rustup target add wasm32-unknown-unknown
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall trunk
      - run: trunk build --release

      - name: Deploy with SCP
        run: |
          scp -r ./dist/* deploy@oncartforthee.ca:/var/www/oncartforthee.ca
