name: On Cart For Thee - CI/CD

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Only deploy on the default branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Trunk Install
        run: cargo binstall trunk

      - name: Trunk Build
        run: trunk build --release

      - name: Deploy with SCP
        run: |
          scp -r ./dist/* deploy@oncartforthee.ca:/var/www/oncartforthee.ca
