name: CI/CD

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall trunk --force
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "wasm32-release"
      - run: trunk build --release
      - uses: actions/upload-artifact@v3
        with:
          name: dist-${{ github.sha }}
          path: dist
  deployment:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist-${{ github.sha }}
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Add SSH host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEYSCAN }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Deploy with SCP
        run: scp -r ./dist/* deploy@oncartforthee.ca:/var/www/oncartforthee.ca
