name: On Cart For Thee - CI/CD

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy on the default branch
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - run: rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall trunk --force
      - run: trunk build --release
      - name: Add SSH host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H oncartforthee.ca >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Deploy with SCP
        run: scp -r ./dist/* deploy@oncartforthee.ca:/var/www/oncartforthee.ca
